export const countries = [
  { code: 'SA', name_ar: 'السعودية', name_en: 'Saudi Arabia' },
  { code: 'EG', name_ar: 'مصر', name_en: 'Egypt' },
  { code: 'AE', name_ar: 'الإمارات', name_en: 'United Arab Emirates' },
  { code: 'KW', name_ar: 'الكويت', name_en: 'Kuwait' },
  { code: 'QA', name_ar: 'قطر', name_en: 'Qatar' },
  { code: 'BH', name_ar: 'البحرين', name_en: 'Bahrain' },
  { code: 'OM', name_ar: 'عمان', name_en: 'Oman' },
  { code: 'YE', name_ar: 'اليمن', name_en: 'Yemen' },
  { code: 'JO', name_ar: 'الأردن', name_en: 'Jordan' },
  { code: 'LB', name_ar: 'لبنان', name_en: 'Lebanon' },
  { code: 'SY', name_ar: 'سوريا', name_en: 'Syria' },
  { code: 'IQ', name_ar: 'العراق', name_en: 'Iraq' },
  { code: 'PS', name_ar: 'فلسطين', name_en: 'Palestine' },
  { code: 'SD', name_ar: 'السودان', name_en: 'Sudan' },
  { code: 'LY', name_ar: 'ليبيا', name_en: 'Libya' },
  { code: 'MA', name_ar: 'المغرب', name_en: 'Morocco' },
  { code: 'TN', name_ar: 'تونس', name_en: 'Tunisia' },
  { code: 'DZ', name_ar: 'الجزائر', name_en: 'Algeria' },
  { code: 'MR', name_ar: 'موريتانيا', name_en: 'Mauritania' },
  { code: 'SO', name_ar: 'الصومال', name_en: 'Somalia' },
  { code: 'DJ', name_ar: 'جيبوتي', name_en: 'Djibouti' },
  { code: 'KM', name_ar: 'جزر القمر', name_en: 'Comoros' },
  { code: 'US', name_ar: 'الولايات المتحدة', name_en: 'United States' },
  { code: 'GB', name_ar: 'المملكة المتحدة', name_en: 'United Kingdom' },
  { code: 'CA', name_ar: 'كندا', name_en: 'Canada' },
  { code: 'FR', name_ar: 'فرنسا', name_en: 'France' },
  { code: 'DE', name_ar: 'ألمانيا', name_en: 'Germany' },
  { code: 'IT', name_ar: 'إيطاليا', name_en: 'Italy' },
  { code: 'ES', name_ar: 'إسبانيا', name_en: 'Spain' },
  { code: 'TR', name_ar: 'تركيا', name_en: 'Turkey' },
  { code: 'IN', name_ar: 'الهند', name_en: 'India' },
  { code: 'PK', name_ar: 'باكستان', name_en: 'Pakistan' },
  { code: 'BD', name_ar: 'بنغلاديش', name_en: 'Bangladesh' },
  { code: 'ID', name_ar: 'إندونيسيا', name_en: 'Indonesia' },
  { code: 'MY', name_ar: 'ماليزيا', name_en: 'Malaysia' },
  { code: 'PH', name_ar: 'الفلبين', name_en: 'Philippines' },
  { code: 'CN', name_ar: 'الصين', name_en: 'China' },
  { code: 'JP', name_ar: 'اليابان', name_en: 'Japan' },
  { code: 'KR', name_ar: 'كوريا الجنوبية', name_en: 'South Korea' },
  { code: 'AU', name_ar: 'أستراليا', name_en: 'Australia' },
  { code: 'NZ', name_ar: 'نيوزيلندا', name_en: 'New Zealand' },
  { code: 'RU', name_ar: 'روسيا', name_en: 'Russia' },
  { code: 'UA', name_ar: 'أوكرانيا', name_en: 'Ukraine' },
  { code: 'BR', name_ar: 'البرازيل', name_en: 'Brazil' },
  { code: 'AR', name_ar: 'الأرجنتين', name_en: 'Argentina' },
  { code: 'MX', name_ar: 'المكسيك', name_en: 'Mexico' },
  { code: 'ZA', name_ar: 'جنوب أفريقيا', name_en: 'South Africa' },
  { code: 'NG', name_ar: 'نيجيريا', name_en: 'Nigeria' },
  { code: 'ET', name_ar: 'إثيوبيا', name_en: 'Ethiopia' },
  { code: 'KE', name_ar: 'كينيا', name_en: 'Kenya' }
].sort((a, b) => a.name_ar.localeCompare(b.name_ar));
